//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyntraExcelAddin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyntraExcelAddin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Value by Validation Master BAG; Please correct Brand, Article Type and Gender Combination..
        /// </summary>
        internal static string ValidationErrorMessage_BAG {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_BAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Value by Validation Master BmTarget; Please correct Brand, Article Type, Gender, Repeated and BM Target Combination..
        /// </summary>
        internal static string ValidationErrorMessage_BMTarget {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_BMTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Value by Validation Master BodyCode; Please correct Article Type, Gender and BodyCode Combination..
        /// </summary>
        internal static string ValidationErrorMessage_BodyCode {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_BodyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Value by Validation Master Cluster; Please correct Gender and Cluster Combination..
        /// </summary>
        internal static string ValidationErrorMessage_Cluster {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Value by Validation Master Color; Please correct Gender and Color Combination..
        /// </summary>
        internal static string ValidationErrorMessage_Color {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Value by Validation Master MoQ; Please correct Brand, Article Type, Gender, Subcategory and Quantity Combination..
        /// </summary>
        internal static string ValidationErrorMessage_Quantity {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected value of Sizetype.
        /// </summary>
        internal static string ValidationErrorMessage_SizeType {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_SizeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Value by Validation Master Subcategory; Please correct Brand, Article Type, Gender and Subcategory Combination..
        /// </summary>
        internal static string ValidationErrorMessage_SubCategory {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_SubCategory", resourceCulture);
            }
        }
    }
}
